#!/usr/bin/env node
/**
 * Run the multi-timeframe strategy over historical bars.
 *
 *   npm run backtest                        # simulated data, all symbols
 *   npm run backtest -- --symbols VXTQ,TRAQ
 *   npm run backtest -- --slippage 0.1 --commission 0.005
 *   npm run backtest -- --provider tradier --symbols AAPL,MSFT
 *   npm run backtest -- --sweep retrace     # vary one threshold, compare
 *
 * ## Read the header before the numbers
 *
 * On the default provider these are **simulated bars**, generated by a process
 * that deliberately builds higher highs and higher lows with pullbacks in them
 * — the exact structure this strategy looks for. Scoring the strategy against
 * them measures how well it finds a pattern that was planted for it. The run
 * is worth doing because it proves the mechanics and shows what costs do to a
 * strategy with sub-1% stops; it is not evidence the strategy makes money, and
 * the output says so every time.
 */

import {
  backtest,
  combine,
  summarize,
  hasLookahead,
  resolveLadder,
  DEFAULT_BACKTEST_CONFIG,
} from '../lib/backtest.js';
import { DEFAULT_TREND_CONFIG, LADDERS } from '../lib/trend.js';
import * as mockProvider from '../lib/providers/mock.js';
import * as tradierProvider from '../lib/providers/tradier.js';
import * as liveProvider from '../lib/providers/live.js';

/* ---------------- arguments ---------------- */

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (!token.startsWith('--')) continue;
    const key = token.slice(2);
    const next = argv[i + 1];
    if (next === undefined || next.startsWith('--')) {
      args[key] = true;
    } else {
      args[key] = next;
      i += 1;
    }
  }
  return args;
}

const args = parseArgs(process.argv.slice(2));
const provider = String(args.provider ?? 'mock').toLowerCase();
const isSimulated = provider === 'mock';

// Simulated bars are phased on the wall clock, so two runs minutes apart are
// two different samples of the same generator. That is a feature here: it is
// the cheapest honest way to show how wide the noise band around any single
// backtest number really is. See --repeats.
const repeats = (() => {
  const asked = Math.max(1, Math.round(Number(args.repeats ?? 1)) || 1);
  if (asked > 1 && !isSimulated) {
    console.log('--repeats only means something on simulated data; a live feed serves the same bars every time.');
    return 1;
  }
  return asked;
})();

const backtestConfig = {
  ...DEFAULT_BACKTEST_CONFIG,
  ...(args.slippage !== undefined ? { slippagePct: Number(args.slippage) } : {}),
  ...(args.commission !== undefined ? { commissionPerShare: Number(args.commission) } : {}),
  ...(args.warmup !== undefined ? { warmupBars: Number(args.warmup) } : {}),
  ...(args.optimistic ? { pessimisticBars: false } : {}),
  ...(args.overnight ? { flattenAtSessionEnd: false } : {}),
  ...(args.ladder && args.ladder !== true
    ? { ladder: LADDERS[args.ladder] ?? String(args.ladder).split(/[\s,]+/).filter(Boolean) }
    : {}),
};

const ladder = resolveLadder(backtestConfig.ladder);
// Bars can be combined but never split, so the fetch has to be at least as
// fine as the ladder's fastest rung.
const ORDER = ['1m', '5m', '15m', '30m', '1h', '4h', '1d'];
const finest =
  ladder.filter((key) => key !== '1d').sort((a, b) => ORDER.indexOf(a) - ORDER.indexOf(b))[0] ?? '1h';

/* ---------------- data ---------------- */

async function loadAll(at) {
  const loaded = [];
  for (const symbol of symbols) {
    try {
      const history = await loadHistory(symbol, at);
      if (history.intraday?.length) loaded.push(history);
      else if (at === now) console.log(`  ${symbol}: no intraday history, skipped`);
    } catch (error) {
      if (at === now) console.log(`  ${symbol}: ${error.message}`);
    }
  }
  return loaded;
}

async function loadHistory(symbol, now) {
  if (provider === 'tradier') return tradierProvider.getHistory({ symbol, interval: finest, now });
  if (provider === 'yahoo') return liveProvider.getHistory({ symbol, interval: finest });
  return mockProvider.getHistory({
    symbol,
    now,
    interval: finest,
    // A 1-minute replay is five times the bars of a 5-minute one, so the
    // simulated window shortens to keep a full run inside a coffee break.
    sessions: Number(args.sessions ?? (finest === '1m' ? 5 : 12)),
  });
}

function universe() {
  if (args.symbols && args.symbols !== true) {
    return String(args.symbols).split(/[\s,]+/).filter(Boolean).map((s) => s.toUpperCase());
  }
  if (!isSimulated) {
    throw new Error('A live provider needs --symbols; free feeds do not stream the whole market.');
  }
  return mockProvider.symbols;
}

/* ---------------- formatting ---------------- */

const pad = (value, width, left = false) => {
  const text = String(value);
  return left ? text.padEnd(width) : text.padStart(width);
};

const signed = (value, digits = 2) =>
  Number.isFinite(value) ? `${value > 0 ? '+' : ''}${value.toFixed(digits)}` : '—';

function printStats(label, stats) {
  if (!stats.trades) {
    console.log(`${label}: no trades taken.`);
    return;
  }
  console.log(
    `${pad(label, 22, true)} ${pad(stats.trades, 6)} trades  ` +
      `${pad(`${stats.winRatePct}%`, 7)} win  ` +
      `${pad(signed(stats.totalR), 9)}R total  ` +
      `${pad(signed(stats.expectancyR, 3), 8)}R/trade  ` +
      `PF ${pad(stats.profitFactor ?? '—', 5)}  ` +
      `maxDD ${pad(stats.maxDrawdownR, 6)}R`,
  );
}

/* ---------------- run ---------------- */

const now = Date.parse(String(args.at ?? '')) || Date.now();
const symbols = universe();

console.log('');
console.log('════════════════════════════════════════════════════════════════════════');
if (isSimulated) {
  console.log('  SIMULATED DATA — these results are not evidence of anything.');
  console.log('');
  console.log('  The bars come from providers/mock.js, which generates trends with');
  console.log('  higher highs, higher lows and pullbacks in them on purpose. This');
  console.log('  strategy detects exactly that structure, so it is being scored on');
  console.log('  finding a pattern that was planted for it to find.');
  console.log('');
  console.log('  What the run does establish: the replay mechanics are sound, there');
  console.log('  is no lookahead, and costs bite a sub-1% stop hard. For anything');
  console.log('  about profitability, run it against real bars:');
  console.log('    node scripts/backtest.mjs --provider yahoo --symbols AAPL,MSFT');
} else {
  console.log(`  LIVE HISTORY via ${provider}. Past bars, not future ones — a backtest`);
  console.log('  measures a rule set against what already happened, and nothing else.');
}
console.log('════════════════════════════════════════════════════════════════════════');
console.log('');

const histories = await loadAll(now);

if (!histories.length) {
  console.error('No history loaded — nothing to test.');
  process.exit(1);
}

// The honesty check comes first, because if it fails nothing below is worth
// reading.
const leaky = histories
  .map((history) => ({ symbol: history.symbol, ...hasLookahead(history, { backtest: backtestConfig }) }))
  .filter((check) => check.leaks);

if (leaky.length) {
  console.error(`LOOKAHEAD DETECTED in ${leaky.length} symbol(s): ${leaky.map((l) => l.symbol).join(', ')}`);
  console.error('The replay is reading bars that had not printed. Results suppressed.');
  process.exit(2);
}
console.log(`Lookahead check: clean across ${histories.length} symbols.`);
console.log(`Ladder: ${ladder.join(' → ')}  (${finest} bars from the feed, coarser rungs resampled)`);

const started = Date.now();
const runs = histories.map((history) => backtest(history, { backtest: backtestConfig, trend: {} }));
const portfolio = combine(runs);
const elapsed = ((Date.now() - started) / 1000).toFixed(1);

console.log(
  `Replayed ${portfolio.bars.toLocaleString('en-US')} bars across ${portfolio.symbols} symbols ` +
    `(${portfolio.decisions.toLocaleString('en-US')} decisions) in ${elapsed}s.`,
);
console.log('');

/* ---------------- what the strategy said ---------------- */

console.log('What the strategy saw, per decision bar');
console.log('──────────────────────────────────────');
const totalDecisions = Object.values(portfolio.states).reduce((a, b) => a + b, 0) || 1;
for (const [state, count] of Object.entries(portfolio.states).sort((a, b) => b[1] - a[1])) {
  const share = ((count / totalDecisions) * 100).toFixed(1);
  console.log(`  ${pad(state, 18, true)} ${pad(count.toLocaleString('en-US'), 8)}  ${pad(`${share}%`, 7)}`);
}
console.log('');

/* ---------------- results ---------------- */

console.log('Results');
console.log('───────');
printStats('All trades', portfolio.stats);

const longs = portfolio.trades.filter((t) => t.direction === 'long');
const shorts = portfolio.trades.filter((t) => t.direction === 'short');
if (longs.length) printStats('  long', summarize(longs));
if (shorts.length) printStats('  short', summarize(shorts));
console.log('');

if (portfolio.stats.trades) {
  console.log(`  Average winner  ${signed(portfolio.stats.avgWinR)}R`);
  console.log(`  Average loser   ${signed(-portfolio.stats.avgLossR)}R`);
  // The unit is the timing rung's bar, which is not always five minutes.
  console.log(`  Bars held       ${portfolio.stats.avgBarsHeld} (${ladder.at(-1)} bars)`);
  console.log(`  Exits           ${Object.entries(portfolio.stats.byReason).map(([k, v]) => `${k} ${v}`).join(', ')}`);
  console.log('');

  // The one slice worth printing by default: the strategy's own caution about
  // pullback depth is either predictive or it is noise, and this says which.
  const cautioned = portfolio.trades.filter((t) => t.cautioned);
  const clean = portfolio.trades.filter((t) => !t.cautioned);
  if (cautioned.length && clean.length) {
    console.log('Does the "measured move is too small" caution predict anything?');
    console.log('─────────────────────────────────────────────────────────────');
    printStats('  no caution', summarize(clean));
    printStats('  cautioned', summarize(cautioned));
    console.log('');
  }
}

/* ---------------- cost sensitivity ---------------- */

if (!args['no-costs']) {
  console.log('Cost sensitivity (slippage per side, applied to every fill)');
  console.log('──────────────────────────────────────────────────────────');
  for (const slippagePct of [0, 0.02, 0.05, 0.1, 0.2]) {
    const runsAt = histories.map((history) =>
      backtest(history, { backtest: { ...backtestConfig, slippagePct }, trend: {} }),
    );
    printStats(`  ${slippagePct.toFixed(2)}%`, combine(runsAt).stats);
  }
  console.log('');
  console.log('  A strategy whose stops are a few tenths of a percent wide spends a');
  console.log('  large fraction of every R on the spread. That is a property of the');
  console.log('  rules, and it holds on real data too.');
  console.log('');
}

/* ---------------- sampling noise ---------------- */

if (repeats > 1) {
  console.log(`Sampling noise: the same rules over ${repeats} independently phased samples`);
  console.log('────────────────────────────────────────────────────────────────────────');

  const totals = [portfolio.stats.totalR];
  printStats('  sample 1', portfolio.stats);

  for (let r = 1; r < repeats; r += 1) {
    // 41 minutes apart: far enough to decorrelate the generator's pullback
    // phase, and not a multiple of any cycle length it uses.
    const at = now - r * 41 * 60_000;
    const sample = combine((await loadAll(at)).map((h) => backtest(h, { backtest: backtestConfig, trend: {} })));
    totals.push(sample.stats.totalR);
    printStats(`  sample ${r + 1}`, sample.stats);
  }

  const sorted = [...totals].sort((a, b) => a - b);
  const median = sorted[Math.floor(sorted.length / 2)];
  console.log('');
  console.log(`  Range ${signed(sorted[0])}R to ${signed(sorted.at(-1))}R, median ${signed(median)}R.`);
  console.log('');
  console.log('  Same rules, same generator, same number of trades — only the phase of');
  console.log('  the data differs. A spread this wide across samples is what a couple of');
  console.log('  hundred trades actually buys you, and it is the reason a single');
  console.log('  backtest figure should never be quoted without one.');
  console.log('');
}

/* ---------------- optional threshold sweep ---------------- */

if (args.sweep) {
  const sweeps = {
    retrace: { key: 'maxRetracePct', values: [38.2, 50, 61.8, 78.6] },
    minretrace: { key: 'minRetracePct', values: [0, 10, 15, 25, 35] },
    bars: { key: 'maxPullbackBars', values: [4, 8, 12, 20] },
    swing: { key: 'swingSpan', values: [1, 2, 3, 4] },
  };
  const sweep = sweeps[String(args.sweep).toLowerCase()];
  if (!sweep) {
    console.log(`Unknown sweep. Options: ${Object.keys(sweeps).join(', ')}`);
  } else {
    console.log(`Sweeping ${sweep.key} (default ${DEFAULT_TREND_CONFIG[sweep.key]})`);
    console.log('──────────────────────────────────────');
    for (const value of sweep.values) {
      const runsAt = histories.map((history) =>
        backtest(history, { backtest: backtestConfig, trend: { [sweep.key]: value } }),
      );
      printStats(`  ${sweep.key}=${value}`, combine(runsAt).stats);
    }
    console.log('');
    console.log('  Picking the best row here is curve fitting: with this few trades the');
    console.log('  differences are inside the noise, and on simulated data the winner is');
    console.log('  whichever value best matches the generator. Use a sweep to see whether');
    console.log('  a rule matters at all, never to choose its value.');
    console.log('');
  }
}

if (isSimulated) {
  console.log('Reminder: simulated bars. Nothing above predicts anything.');
  console.log('');
}
