/**
 * Walk-forward backtest for the multi-timeframe strategy.
 *
 * ## What this can and cannot tell you
 *
 * A backtest measures a rule set against a price series. It does not measure
 * the rule set against the future, and on **simulated** data it does not even
 * measure it against a market — the simulated bars in providers/mock.js are
 * generated by a process that puts higher highs and higher lows into the
 * series on purpose, which is precisely the structure this strategy detects.
 * Run against them, the strategy is being scored on how well it finds a
 * pattern that was placed there for it to find. The results will look good and
 * they will mean nothing about real trading.
 *
 * What a run on simulated data *is* good for:
 *   - proving the mechanics work end to end: orders fill, stops and targets
 *     resolve, and the accounting balances
 *   - proving there is no lookahead — see `hasLookahead` below, and the test
 *     that asserts a bar's verdict does not change when future bars exist
 *   - showing how sensitive a strategy with sub-1% stops is to costs, which is
 *     a property of the rules and not of the data
 *
 * Point it at real bars via the live providers before drawing any conclusion
 * about whether the strategy makes money.
 *
 * ## The replay
 *
 * One bar at a time. At each bar the engine hands the strategy *only* the bars
 * up to and including that one, takes whatever setup comes back, and rests a
 * stop order. Fills, stops and targets are then resolved on later bars using
 * that bar's own high and low.
 *
 * Where a single bar is ambiguous — its range covers both the stop and a
 * target, so the order they were touched in is unknowable from OHLC — the
 * engine assumes the stop. That is not pessimism for its own sake: the
 * opposite assumption turns every losing trade that briefly traded green into
 * a winner, which is the single easiest way to make a backtest lie.
 */

import { buildLadder, easternParts } from './timeframes.js';
import {
  analyzeLadder,
  readWindow,
  LADDERS,
  DEFAULT_LADDER,
  DEFAULT_TREND_CONFIG,
} from './trend.js';

export const DEFAULT_BACKTEST_CONFIG = {
  // Enough bars for the hourly series to reach the moving-average minimum:
  // ~21 hourly bars is 252 five-minute bars.
  warmupBars: 300,
  ladder: DEFAULT_LADDER, // a name from LADDERS, or an explicit array of intervals
  // Bars handed to the strategy each step. Null derives it from the ladder,
  // which is almost always what you want — see lookbackFor.
  maxIntradayLookback: null,
  orderLifeBars: 6, // a resting trigger that has not filled is cancelled
  maxHoldBars: 78, // a continuation that has not worked in this many bars has not worked
  // Flatten at the closing bell rather than carrying the position overnight.
  //
  // `maxHoldBars` alone does not do this, and the difference is expensive:
  // bars only accrue while the market is open, so 78 five-minute bars from a
  // 15:00 entry expires at 15:00 *the next day*. On real data the eleven
  // trades that were carried overnight averaged -2.36R against -0.50R for the
  // ones closed the same session, because an overnight gap goes straight
  // through a stop that is a few tenths of a percent wide. A strategy timed
  // on 5-minute bars is not being paid to take that risk.
  flattenAtSessionEnd: true,
  targetRatios: [2, 3],
  scaleOutPct: 50, // share of the position taken off at the first target
  breakevenAfterFirstTarget: true,
  slippagePct: 0.05, // adverse, applied to every fill, both sides
  commissionPerShare: 0,
  pessimisticBars: true, // an ambiguous bar resolves against the trade
  exitOnInvalidation: false, // also exit when hourly structure breaks while in a position
};

/** A ladder name, an explicit list of intervals, or the default. */
export function resolveLadder(ladder) {
  if (Array.isArray(ladder) && ladder.length >= 2) return ladder;
  if (typeof ladder === 'string' && LADDERS[ladder]) return LADDERS[ladder];
  return LADDERS[DEFAULT_LADDER];
}

const INTERVAL_MINUTES = { '1m': 1, '5m': 5, '15m': 15, '30m': 30, '1h': 60, '4h': 240 };

/**
 * How many of the finest bars the slowest intraday rung needs.
 *
 * A fixed number cannot serve every ladder. The swing ladder's hourly rung
 * wants 90 bars, which is 1,080 five-minute bars; the scalp ladder's
 * 15-minute rung wants 90 bars, which is 1,350 *one*-minute bars. Handing over
 * a flat 1,200 quietly starves the slowest rung on the fast ladders — it still
 * produces a verdict, from a shorter history than the live scanner would use,
 * so the backtest measures something subtly different from what it is meant to.
 *
 * The slack covers session gaps: a rung's window is in bars, and bars only
 * accrue during the session, so the wall-clock span they cover is longer than
 * the arithmetic suggests.
 */
export function lookbackFor(ladder, trendConfig = {}) {
  const intraday = ladder.filter((key) => INTERVAL_MINUTES[key]);
  if (!intraday.length) return 400;

  const finest = Math.min(...intraday.map((key) => INTERVAL_MINUTES[key]));
  const needed = Math.max(
    ...intraday.map((key) => readWindow(key, trendConfig) * (INTERVAL_MINUTES[key] / finest)),
  );
  return Math.ceil(needed * 1.2) + 60;
}

/**
 * The first bar at which every rung is readable at all.
 *
 * Not the same as the lookback, and deliberately much smaller. The lookback is
 * how much history the strategy gets to *see*; this is the point before which
 * it would refuse to look, because a rung with fewer bars than `minBars` or
 * the slow moving-average period comes back `unusable` rather than wrong.
 *
 * Waiting for the full window instead would be stricter than the live scanner
 * — which reads whatever it has, subject to those same guards — and on a
 * finite series it costs decisions for nothing: the guards already prevent a
 * thin rung from producing a verdict.
 */
export function warmupFor(ladder, trendConfig = {}) {
  const intraday = ladder.filter((key) => INTERVAL_MINUTES[key]);
  if (!intraday.length) return 60;

  const finest = Math.min(...intraday.map((key) => INTERVAL_MINUTES[key]));
  const cfg = { ...DEFAULT_TREND_CONFIG, ...trendConfig };
  const readable = Math.max(cfg.minBars, cfg.slowPeriod) + cfg.swingSpan * 2;
  const needed = Math.max(...intraday.map((key) => readable * (INTERVAL_MINUTES[key] / finest)));
  return Math.ceil(needed * 1.15) + 30;
}

function normalizeConfig(config = {}) {
  const merged = { ...DEFAULT_BACKTEST_CONFIG, ...config };
  for (const [key, fallback] of Object.entries(DEFAULT_BACKTEST_CONFIG)) {
    if (key === 'ladder') {
      merged.ladder = resolveLadder(merged.ladder);
      continue;
    }
    if (key === 'maxIntradayLookback') continue; // derived below, once the ladder is known
    if (typeof fallback === 'boolean') {
      merged[key] = Boolean(merged[key]);
      continue;
    }
    if (Array.isArray(fallback)) {
      const list = Array.isArray(merged[key]) ? merged[key].map(Number).filter((n) => n > 0) : [];
      merged[key] = list.length ? list.sort((a, b) => a - b) : fallback;
      continue;
    }
    const value = Number(merged[key]);
    // Zero is meaningful for costs, so only reject negatives and nonsense.
    merged[key] = Number.isFinite(value) && value >= 0 ? value : fallback;
  }

  const explicit = Number(config.maxIntradayLookback);
  merged.maxIntradayLookback =
    Number.isFinite(explicit) && explicit > 0 ? explicit : lookbackFor(merged.ladder, config.trend);

  // Raise the warmup only when the ladder genuinely needs it — a 1-minute
  // ladder reaching a 15-minute rung needs three times the bars a 5-minute one
  // does before that rung says anything at all.
  merged.warmupBars = Math.max(merged.warmupBars, warmupFor(merged.ladder, config.trend));
  return merged;
}

function round(value, digits = 2) {
  if (!Number.isFinite(value)) return null;
  const factor = 10 ** digits;
  return Math.round(value * factor) / factor;
}

/* ------------------------------------------------------------------ */
/* fills                                                               */
/* ------------------------------------------------------------------ */

/**
 * Price a fill, always against the trade.
 *
 * A stop order that gaps through its trigger fills at the open, not the
 * trigger — modelling it at the trigger price hands the backtest free money on
 * exactly the bars where a real account loses the most.
 */
function fillPrice(bar, level, { direction, kind, ignoreOpen = false }) {
  const long = direction === 'long';
  // Every order type reduces to one question: does price have to rise or fall
  // to reach this level? A long's entry and target are above it and its stop
  // is below; for a short each is the other way round.
  const rising = kind === 'stop_loss' ? !long : long;

  // Opening past the level means the order filled at the open, not at the
  // level. On a stop that is the gap that costs more than a full R; pricing it
  // at the level hands the backtest free money on exactly those bars.
  //
  // `ignoreOpen` is for the bar the trade got in on. The position did not
  // exist when that bar opened, so an open below a long's stop is not a gap
  // through the stop — it is simply where the bar started before rallying into
  // the entry. Treating it as a gap stops out every trade that fills on a bar
  // which opened weak, which is most of them.
  if (!ignoreOpen) {
    const gapped = rising ? bar.open >= level : bar.open <= level;
    if (gapped) return bar.open;
  }

  const touched = rising ? bar.high >= level : bar.low <= level;
  return touched ? level : null;
}

/** Slippage always moves the fill against the trade, entering and exiting. */
function withSlippage(price, direction, side, slippagePct) {
  const adverse = (direction === 'long') === (side === 'entry') ? 1 : -1;
  return price * (1 + (adverse * slippagePct) / 100);
}

/* ------------------------------------------------------------------ */
/* the replay                                                          */
/* ------------------------------------------------------------------ */

/**
 * What the strategy could legitimately see at one bar.
 *
 * The single place the replay decides what "now" means, so the lookahead check
 * below tests the real path rather than a copy of it that might drift from it.
 *
 * The daily filter is subtler than it looks. A daily bar is dated to its day
 * with no time, so *today's* bar is stamped before this moment and survives the
 * cutoff — and a provider's copy of it carries the whole session's high and
 * low, which at 10:30 in the morning is tomorrow's information. What saves it
 * is `mergeDaily`, which throws that bar away and rebuilds today from the
 * intraday bars, and those are already truncated. The filter handles later
 * days; mergeDaily handles today.
 */
function analysisAt(intraday, daily, index, cfg, trendConfig) {
  const bar = intraday[index];
  const cutoff = new Date(bar.time).getTime();
  const from = Math.max(0, index + 1 - cfg.maxIntradayLookback);

  return analyzeLadder(
    buildLadder({
      ladder: cfg.ladder,
      intraday: intraday.slice(from, index + 1),
      daily: daily.filter((d) => new Date(d.time).getTime() <= cutoff),
      now: cutoff,
    }),
    trendConfig,
  );
}

/**
 * Replay one instrument.
 *
 * `history` is `{ intraday, daily }` exactly as a provider's getHistory
 * returns it. Returns the closed trades, a per-bar tally of what the strategy
 * said, and the statistics derived from both.
 */
export function backtest(history, options = {}) {
  const cfg = normalizeConfig(options.backtest);
  const trendConfig = options.trend ?? {};
  const symbol = history.symbol ?? options.symbol ?? null;

  const intraday = (Array.isArray(history.intraday) ? history.intraday : []).filter(
    (bar) => bar && Number.isFinite(bar.high) && Number.isFinite(bar.low) && Number.isFinite(bar.close),
  );
  const daily = Array.isArray(history.daily) ? history.daily : [];

  const trades = [];
  const states = {};
  let decisions = 0;

  const warmup = Math.max(Math.round(cfg.warmupBars), 1);

  for (let i = warmup; i < intraday.length; i += 1) {
    // The strategy is only asked when there is nothing working — a resting
    // order or an open position owns the bars it spans, and re-analysing them
    // would let a second trade start inside the first.
    const analysis = analysisAt(intraday, daily, i, cfg, trendConfig);
    decisions += 1;
    states[analysis.state] = (states[analysis.state] ?? 0) + 1;
    if (!analysis.setup) continue;

    const outcome = simulateTrade(
      {
        direction: analysis.setup.direction,
        entry: analysis.setup.entry,
        stop: analysis.setup.stop,
        state: analysis.state,
        retracePct: analysis.setup.retracePct,
        legPct: analysis.setup.impulsePct,
        measuredR: analysis.setup.measuredR,
        cautioned: (analysis.setup.cautions ?? []).length > 0,
        placedAt: intraday[i].time,
      },
      intraday,
      i + 1,
      cfg,
    );

    if (outcome.trade) trades.push(outcome.trade);
    // Skip past whatever the order consumed — the next decision is the first
    // bar after it resolved.
    i = outcome.endIndex;
  }

  return {
    symbol,
    ladder: cfg.ladder,
    bars: intraday.length,
    decisions,
    states,
    trades,
    stats: summarize(trades),
  };
}

/**
 * Follow one resting order forward until it fills and closes, or expires.
 *
 * Separated from the walk-forward loop because this is where a backtest most
 * easily flatters itself, and it is worth being able to test each rule against
 * a hand-built bar in isolation: the gap fill, the ambiguous bar, the
 * scale-out, the breakeven stop.
 *
 * Returns `{ trade, endIndex }`. `trade` is null when the order expired
 * unfilled; `endIndex` is the last bar the order occupied either way.
 */
export function simulateTrade(order, bars, startIndex, config = {}) {
  const cfg = normalizeConfig(config);
  let position = null;

  for (let i = startIndex; i < bars.length; i += 1) {
    const bar = bars[i];

    if (!position) {
      if (i - startIndex >= cfg.orderLifeBars) return { trade: null, endIndex: i };

      const raw = fillPrice(bar, order.entry, { direction: order.direction, kind: 'buy_stop' });
      if (raw === null) continue;

      position = openPosition(order, raw, bar, i, cfg);
      // A bar wide enough to fill the entry and then reach the stop is
      // resolved against the trade. The low may well have printed before the
      // entry did, but OHLC cannot say, and assuming otherwise is how a
      // backtest turns its losers into winners.
      const closed = stepPosition(position, bar, i, cfg, { entryBar: true });
      if (closed) return { trade: closed, endIndex: i };
      continue;
    }

    const closed = stepPosition(position, bar, i, cfg);
    if (closed) return { trade: closed, endIndex: i };

    // Last bar of its session: flatten at the close rather than carry the gap.
    if (cfg.flattenAtSessionEnd && isSessionEnd(bars, i)) {
      return { trade: closeOut(position, bar.close, i, bar.time, 'session_end', cfg), endIndex: i };
    }
  }

  // An open position at the end of the data is marked to the last close rather
  // than dropped: dropping it quietly discards whichever trades happened to be
  // going worst at the moment the data ran out.
  const last = bars.length - 1;
  if (position) {
    return {
      trade: closeOut(position, bars[last].close, last, bars[last].time, 'end_of_data', cfg),
      endIndex: last,
    };
  }
  return { trade: null, endIndex: last };
}

/** True when the next bar starts a different Eastern trading day. */
function isSessionEnd(bars, index) {
  const next = bars[index + 1];
  if (!next) return false; // end of data is handled separately
  return easternParts(bars[index].time)?.date !== easternParts(next.time)?.date;
}

/**
 * Open a position, with R measured against the risk that was *planned*.
 *
 * This is the modelling choice that matters most in this file. Size is decided
 * when the order is placed, from the setup's own entry-to-stop distance, and
 * it does not change because the fill came in badly. So a stop order that gaps
 * two points through its trigger fills higher while the stop stays where it
 * was, and the account loses more than one R on it.
 *
 * Measuring R against the *actual* fill would quietly relabel that as a
 * textbook -1R loss. Every gap and every tick of slippage would vanish into
 * the denominator, and the backtest would report a strategy nobody could have
 * traded. Planned risk keeps those costs visible where they belong.
 */
function openPosition(order, rawFill, bar, index, cfg) {
  const entry = withSlippage(rawFill, order.direction, 'entry', cfg.slippagePct);
  const risk = Math.abs(order.entry - order.stop);
  const sign = order.direction === 'long' ? 1 : -1;

  return {
    ...order,
    entry,
    plannedEntry: order.entry,
    risk,
    sign,
    stop: order.stop,
    initialStop: order.stop,
    openedAtIndex: index,
    openedAt: bar.time,
    remaining: 1, // fraction of the position still on
    realizedR: 0,
    // Targets sit that many planned-R away from where the trade *actually*
    // got in. Size is fixed by the planned risk, so it takes a move of
    // 2 x plannedRisk from the real fill to bank 2R of real money — measuring
    // from the planned entry instead would credit a gap fill with profit it
    // never made.
    targets: cfg.targetRatios.map((ratio, n) => ({
      ratio,
      price: entry + sign * risk * ratio,
      // The first target takes scaleOutPct off; the last takes whatever is left.
      share: n === 0 && cfg.targetRatios.length > 1 ? cfg.scaleOutPct / 100 : null,
      filled: false,
    })),
  };
}

/**
 * Advance an open position through one bar.
 *
 * Returns the closed trade when the bar finishes it, otherwise null.
 */
function stepPosition(position, bar, index, cfg, { entryBar = false } = {}) {
  const long = position.direction === 'long';

  // Stop first. On a bar whose range covers both the stop and a target there
  // is no way to know which came first, and assuming the target is how a
  // backtest flatters itself.
  const stopFill = fillPrice(bar, position.stop, {
    direction: position.direction,
    kind: 'stop_loss',
    ignoreOpen: entryBar,
  });
  if (stopFill !== null && cfg.pessimisticBars) {
    return closeOut(position, stopFill, index, bar.time, position.stop === position.entry ? 'breakeven_stop' : 'stop', cfg);
  }

  for (const target of position.targets) {
    if (target.filled) continue;
    const fill = fillPrice(bar, target.price, { direction: position.direction, kind: 'take_profit' });
    if (fill === null) break; // targets are ordered; if the near one is unmet the far one is too

    const share = target.share ?? position.remaining;
    const exit = withSlippage(fill, position.direction, 'exit', cfg.slippagePct);
    position.realizedR += (((exit - position.entry) * position.sign) / position.risk) * share;
    position.remaining = round(position.remaining - share, 6);
    target.filled = true;

    if (position.remaining <= 1e-6) {
      return finish(position, index, bar.time, 'target', cfg);
    }
    // Once the first target pays, the rest of the trade is free.
    if (cfg.breakevenAfterFirstTarget) position.stop = position.entry;
  }

  if (!stopFill && !entryBar && index - position.openedAtIndex >= cfg.maxHoldBars) {
    return closeOut(position, bar.close, index, bar.time, 'time', cfg);
  }

  // A non-pessimistic run still has to honour the stop, just after the targets.
  if (stopFill !== null && !cfg.pessimisticBars) {
    return closeOut(position, stopFill, index, bar.time, 'stop', cfg);
  }

  return null;
}

/** Close whatever is left of a position at `price`. */
function closeOut(position, price, index, time, reason, cfg) {
  const exit = withSlippage(price, position.direction, 'exit', cfg.slippagePct);
  position.realizedR += (((exit - position.entry) * position.sign) / position.risk) * position.remaining;
  position.remaining = 0;
  return finish(position, index, time, reason, cfg);
}

function finish(position, index, time, reason, cfg) {
  // Commission is charged in R, since R is the unit everything else is in: a
  // fixed per-share cost is a bigger fraction of a tight stop than a wide one,
  // which is exactly the effect worth seeing.
  const commissionR = position.risk > 0 ? (cfg.commissionPerShare * 2) / position.risk : 0;
  const netR = position.realizedR - commissionR;

  return {
    direction: position.direction,
    entry: round(position.entry, 4),
    plannedEntry: round(position.plannedEntry, 4),
    initialStop: round(position.initialStop, 4),
    // The planned distance, which is what size was set from — see openPosition.
    riskPerShare: round(position.risk, 4),
    openedAt: position.openedAt,
    closedAt: time,
    barsHeld: index - position.openedAtIndex,
    reason,
    grossR: round(position.realizedR, 3),
    r: round(netR, 3),
    win: netR > 0,
    // Carried through from the setup so results can be sliced by what the
    // strategy actually saw when it took the trade.
    setupState: position.state,
    retracePct: position.retracePct,
    legPct: position.legPct,
    measuredR: position.measuredR,
    cautioned: position.cautioned,
  };
}

/* ------------------------------------------------------------------ */
/* statistics                                                          */
/* ------------------------------------------------------------------ */

export function summarize(trades = []) {
  const closed = trades.filter((t) => Number.isFinite(t.r));
  if (!closed.length) {
    return { trades: 0, wins: 0, losses: 0, winRatePct: null, totalR: 0, expectancyR: null };
  }

  const wins = closed.filter((t) => t.r > 0);
  const losses = closed.filter((t) => t.r <= 0);
  const sum = (list) => list.reduce((total, t) => total + t.r, 0);
  const grossWin = sum(wins);
  const grossLoss = Math.abs(sum(losses));

  // Equity in R, walked in time order, so the drawdown is the real one rather
  // than the worst single trade.
  const ordered = [...closed].sort((a, b) => new Date(a.closedAt) - new Date(b.closedAt));
  let equity = 0;
  let peak = 0;
  let maxDrawdownR = 0;
  for (const trade of ordered) {
    equity += trade.r;
    peak = Math.max(peak, equity);
    maxDrawdownR = Math.max(maxDrawdownR, peak - equity);
  }

  const byReason = {};
  for (const trade of closed) byReason[trade.reason] = (byReason[trade.reason] ?? 0) + 1;

  return {
    trades: closed.length,
    wins: wins.length,
    losses: losses.length,
    winRatePct: round((wins.length / closed.length) * 100),
    totalR: round(equity, 2),
    expectancyR: round(equity / closed.length, 3),
    avgWinR: wins.length ? round(grossWin / wins.length, 2) : null,
    avgLossR: losses.length ? round(grossLoss / losses.length, 2) : null,
    // Gross win over gross loss. Below 1 the strategy loses money however good
    // the win rate looks.
    profitFactor: grossLoss > 0 ? round(grossWin / grossLoss, 2) : null,
    maxDrawdownR: round(maxDrawdownR, 2),
    avgBarsHeld: round(closed.reduce((t, x) => t + x.barsHeld, 0) / closed.length, 1),
    byReason,
  };
}

/** Merge per-symbol runs into one portfolio-level result. */
export function combine(runs = []) {
  const trades = runs.flatMap((run) => run.trades.map((t) => ({ ...t, symbol: run.symbol })));
  const states = {};
  for (const run of runs) {
    for (const [state, count] of Object.entries(run.states ?? {})) {
      states[state] = (states[state] ?? 0) + count;
    }
  }
  return {
    symbols: runs.length,
    bars: runs.reduce((total, r) => total + r.bars, 0),
    decisions: runs.reduce((total, r) => total + r.decisions, 0),
    states,
    trades,
    stats: summarize(trades),
    perSymbol: runs.map((run) => ({ symbol: run.symbol, ...run.stats })),
  };
}

/**
 * Prove the replay cannot see the future, by poisoning the future.
 *
 * Comparing "the verdict at bar i" against "the verdict with the whole series
 * present" proves nothing — those are two different moments and they *should*
 * differ. The question is narrower: does the verdict at bar i depend on
 * anything after bar i?
 *
 * So this runs the replay's own view at bar i twice. The second time, every
 * bar after i is replaced with an absurd one and today's daily bar is given
 * the whole session's range — the two ways a provider actually leaks the
 * future into a replay. If the verdict moves at all, something upstream is
 * reading bars that had not printed, and every number this file produces is
 * worthless.
 *
 * Exported rather than kept in the tests because it is worth running against
 * real feeds too, where a provider back-filling a bar reintroduces the problem
 * without anything in this repository changing.
 */
export function hasLookahead(history, { at, trend = {}, backtest: backtestConfig = {} } = {}) {
  const cfg = normalizeConfig(backtestConfig);
  const intraday = history.intraday ?? [];
  const daily = history.daily ?? [];
  const index = at ?? Math.floor(intraday.length * 0.7);
  if (!intraday[index]) throw new Error('No bar at that index to check');

  const cutoffDate = easternParts(intraday[index].time)?.date;

  const poisonedIntraday = intraday.map((bar, i) =>
    i <= index ? bar : { ...bar, open: bar.open * 4, high: bar.high * 4, low: bar.low / 4, close: bar.close * 4 },
  );
  const poisonedDaily = daily.map((bar) => {
    const session = easternParts(bar.time)?.date;
    if (!session || session < cutoffDate) return bar;
    // Today's completed bar, and every day after it, blown out of all
    // proportion. A read that touches either will move.
    return { ...bar, open: bar.open * 4, high: bar.high * 4, low: bar.low / 4, close: bar.close * 4 };
  });

  const clean = analysisAt(intraday, daily, index, cfg, trend);
  const poisoned = analysisAt(poisonedIntraday, poisonedDaily, index, cfg, trend);

  const same =
    clean.state === poisoned.state &&
    clean.direction === poisoned.direction &&
    clean.invalidation === poisoned.invalidation &&
    clean.setup?.entry === poisoned.setup?.entry &&
    clean.setup?.stop === poisoned.setup?.stop;

  return { index, leaks: !same, clean, poisoned };
}
